In [2]:
import pandas as pd

#cria um dataframe instanciando no objeto "df"
df = pd.read_csv("BaseDPEvolucaoMensalCisp (1).csv",sep = ";", encoding = "latin1")
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [5]:
#mostra a quantidade de linhas e colunas da tabela
df.shape

(37314, 65)

In [ ]:
#mostra o nome das colunas
df.columns.tolist()

In [4]:
#mostra o tipo das colunas
df[['mes', 'ano', 'munic', 'regiao', 'furto_veiculos', 'recuperacao_veiculos']].dtypes

mes                     int64
ano                     int64
munic                     str
regiao                    str
furto_veiculos          int64
recuperacao_veiculos    int64
dtype: object

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37314 entries, 0 to 37313
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37314 non-null  int64
 1   mes                         37314 non-null  int64
 2   ano                         37314 non-null  int64
 3   mes_ano                     37314 non-null  str
 4   aisp                        37314 non-null  int64
 5   risp                        37314 non-null  int64
 6   munic                       37314 non-null  str
 7   mcirc                       37314 non-null  int64
 8   regiao                      37314 non-null  str
 9   hom_doloso                  37314 non-null  int64
 10  lesao_corp_morte            37314 non-null  int64
 11  latrocinio                  37314 non-null  int64
 12  cvli                        37314 non-null  int64
 13  hom_por_interv_policial     37314 non-null  int64
 14  feminicidio                 2192 non-null   float64
 15  letalidade_violenta         37314 non-null  int64
 16  tentat_hom                  37314 non-null  int64
 17  tentativa_feminicidio       2192 non-null   float64
 18  lesao_corp_dolosa           37314 non-null  int64
 19  estupro                     37314 non-null  int64
 20  hom_culposo                 37314 non-null  int64
 21  lesao_corp_culposa          37314 non-null  int64
 22  roubo_transeunte            37314 non-null  int64
 23  roubo_celular               37314 non-null  int64
 24  roubo_em_coletivo           37314 non-null  int64
 25  roubo_rua                   37314 non-null  int64
 26  roubo_veiculo               37314 non-null  int64
 27  roubo_carga                 37314 non-null  int64
 28  roubo_comercio              37314 non-null  int64
 29  roubo_residencia            37314 non-null  int64
 30  roubo_banco                 37314 non-null  int64
 31  roubo_cx_eletronico         37295 non-null  float64
 32  roubo_conducao_saque        37314 non-null  int64
 33  roubo_apos_saque            37314 non-null  int64
 34  roubo_bicicleta             19925 non-null  float64
 35  outros_roubos               37314 non-null  int64
 36  total_roubos                37314 non-null  int64
 37  furto_veiculos              37314 non-null  int64
 38  furto_transeunte            37314 non-null  int64
 39  furto_coletivo              37314 non-null  int64
 40  furto_celular               37314 non-null  int64
 41  furto_bicicleta             19925 non-null  float64
 42  outros_furtos               37314 non-null  int64
 43  total_furtos                37314 non-null  int64
 44  sequestro                   37314 non-null  int64
 45  extorsao                    37314 non-null  int64
 46  sequestro_relampago         37314 non-null  int64
 47  estelionato                 37314 non-null  int64
 48  apreensao_drogas            37314 non-null  int64
 49  posse_drogas                32668 non-null  float64
 50  trafico_drogas              32668 non-null  float64
 51  apreensao_drogas_sem_autor  32668 non-null  float64
 52  recuperacao_veiculos        37314 non-null  int64
 53  apf                         32668 non-null  float64
 54  aaapai                      32668 non-null  float64
 55  cmp                         32668 non-null  float64
 56  cmba                        32668 non-null  float64
 57  ameaca                      37314 non-null  int64
 58  pessoas_desaparecidas       37314 non-null  int64
 59  encontro_cadaver            37314 non-null  int64
 60  encontro_ossada             37314 non-null  int64
 61  pol_militares_mortos_serv   37314 non-null  int64
 62  pol_civis_mortos_serv       37314 non-null  int64
 63  registro_ocorrencias        37314 non-null  int64
 64  fase                        37314 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.5 MB

In [6]:
#mostra as estatisticas das colunas (todas ou as que eu selecionar). Neste caso filtrei somente pela de furto e recuperação
df[['mes', 'ano', 'munic', 'regiao', 'furto_veiculos', 'recuperacao_veiculos']].describe().T

,count,mean,std,min,25%,50%,75%,max
mes,37314.0,6.482232,3.461767,1.0,3.0,6.0,9.0,12.0
ano,37314.0,2014.188723,6.625316,2003.0,2008.0,2014.0,2020.0,2026.0
furto_veiculos,37314.0,11.005092,13.832270,0.0,1.0,6.0,16.0,173.0
recuperacao_veiculos,37314.0,13.947044,24.547743,0.0,1.0,4.0,16.0,359.0

In [3]:
#mostra as celulas com valor null ou soma todas
df[['mes', 'ano', 'munic', 'regiao', 'furto_veiculos', 'recuperacao_veiculos']].isnull().sum()

mes                     0
ano                     0
munic                   0
regiao                  0
furto_veiculos          0
recuperacao_veiculos    0
dtype: int64

In [ ]:
#para usar uma coluna especifica, independentemente em qual função, usar dessa forma
df['']

In [7]:
#mostra a soma de todas as linhas das colunas que quiser
print(f"Número total de furto de veículos: {df['furto_veiculos'].sum()}")
print(f"Número total de recuperação de veículos: {df['recuperacao_veiculos'].sum()}")

Número total de furto de veículos: 410644
Número total de recuperação de veículos: 520420

In [65]:
print(f'A média mensal de furtos de veículos no estado do RJ é: {df['furto_veiculos'].mean():.2f}')
print(f'A média mensal de recuperação de veículos no estado do RJ é: {df['recuperacao_veiculos'].mean():.2f}')

A média mensal de furtos de veículos no estado do RJ é: 11.01
A média mensal de recuperação de veículos no estado do RJ é: 13.95

In [19]:
df['regiao'].value_counts()

regiao
Interior                         18192
Capital                          11197
Baixada Fluminense                5155
Grande NiterÃÂÃÂÃÂÃÂ³i     2610
Grande Niterói                     160
Name: count, dtype: int64