In [2]:
import pandas as pd

#cria um dataframe instanciando no objeto "df"
df = pd.read_csv("BaseDPEvolucaoMensalCisp (1).csv",sep = ";", encoding = "latin1")
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [5]:
#mostra a quantidade de linhas e colunas da tabela
df.shape

(37314, 65)

In [3]:
#mostra o nome das colunas
df.columns.tolist()

['cisp',
 'mes',
 'ano',
 'mes_ano',
 'aisp',
 'risp',
 'munic',
 'mcirc',
 'regiao',
 'hom_doloso',
 'lesao_corp_morte',
 'latrocinio',
 'cvli',
 'hom_por_interv_policial',
 'feminicidio',
 'letalidade_violenta',
 'tentat_hom',
 'tentativa_feminicidio',
 'lesao_corp_dolosa',
 'estupro',
 'hom_culposo',
 'lesao_corp_culposa',
 'roubo_transeunte',
 'roubo_celular',
 'roubo_em_coletivo',
 'roubo_rua',
 'roubo_veiculo',
 'roubo_carga',
 'roubo_comercio',
 'roubo_residencia',
 'roubo_banco',
 'roubo_cx_eletronico',
 'roubo_conducao_saque',
 'roubo_apos_saque',
 'roubo_bicicleta',
 'outros_roubos',
 'total_roubos',
 'furto_veiculos',
 'furto_transeunte',
 'furto_coletivo',
 'furto_celular',
 'furto_bicicleta',
 'outros_furtos',
 'total_furtos',
 'sequestro',
 'extorsao',
 'sequestro_relampago',
 'estelionato',
 'apreensao_drogas',
 'posse_drogas',
 'trafico_drogas',
 'apreensao_drogas_sem_autor',
 'recuperacao_veiculos',
 'apf',
 'aaapai',
 'cmp',
 'cmba',
 'ameaca',
 'pessoas_desaparecidas',
 'encontro_cadaver',
 'encontro_ossada',
 'pol_militares_mortos_serv',
 'pol_civis_mortos_serv',
 'registro_ocorrencias',
 'fase']

In [10]:
#mostra o tipo das colunas
df['recuperacao_veiculos'].dtypes

dtype('int64')

In [ ]:
df.info()

In [18]:
#mostra as estatisticas das colunas (todas ou as que eu selecionar). Neste caso filtrei somente pela de furto e recuperação
df[['furto_veiculos','recuperacao_veiculos']].describe().T

,count,mean,std,min,25%,50%,75%,max
furto_veiculos,37314.0,11.005092,13.832270,0.0,1.0,6.0,16.0,173.0
recuperacao_veiculos,37314.0,13.947044,24.547743,0.0,1.0,4.0,16.0,359.0

In [42]:
#mostra as celulas com valor null ou soma todas
df.isnull().sum()

cisp                         0
mes                          0
ano                          0
mes_ano                      0
aisp                         0
                            ..
encontro_ossada              0
pol_militares_mortos_serv    0
pol_civis_mortos_serv        0
registro_ocorrencias         0
fase                         0
Length: 65, dtype: int64

In [ ]:
#para usar uma coluna especifica, independentemente em qual função, usar dessa forma
df['nome_da_coluna']

In [57]:
#mostra a soma de todas as linhas das colunas que quiser
print(f"Número total de furto de veículos: {df['furto_veiculos'].sum()}")
print(f"Número total de recuperação de veículos: {df['recuperacao_veiculos'].sum()}")

Número total de furto de veículos: 410644
Número total de recuperação de veículos: 520420

np.int64(520420)

In [65]:
print(f'A média mensal de furtos de veículos no estado do RJ é: {df['furto_veiculos'].mean():.2f}')
print(f'A média mensal de recuperação de veículos no estado do RJ é: {df['recuperacao_veiculos'].mean():.2f}')

A média mensal de furtos de veículos no estado do RJ é: 11.01
A média mensal de recuperação de veículos no estado do RJ é: 13.95

In [19]:
df['regiao'].value_counts()

regiao
Interior                         18192
Capital                          11197
Baixada Fluminense                5155
Grande NiterÃÂÃÂÃÂÃÂ³i     2610
Grande Niterói                     160
Name: count, dtype: int64